services:
  db:
    image: postgres:16-alpine
    container_name: owasp_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-owasp}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-owasp}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: owasp_web
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/owasp?schema=public}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-supersecret}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${WEB_PORT:-3000}:3000"
    command: >
      sh -c "npx prisma migrate deploy && npm run start"

volumes:
  db-data:
